export enum RoutesTypes {
  HOME = '/home',
  SEARCH = '/search',
  HISTORY_OF_CLAIM = '/history-of-claim',
  HISTORY_OF_DONATE = '/history-of-donate',
  SETTINGS = '/settings',
  READERS = '/readers',
  BOOKS_STUFF = '/books-stuff',
  DONATES_FROM_USER = '/donates-from-user',
  CREATE_NEW_ITEM = '/create-new-item',
  DONATE_TO_LIBRARY = '/donate-to-library',
  DONATE_PREVIEW = '/donate',
  BOOK_PREVIEW = 'item',
  CATEGORY = '/category',
}
