export const resources = {
  en: {
    translation: {
      Back: 'Back',
      Loading: 'Loading...',
      Cancel: 'Cancel',
      EmptyListItems: {
        Header: 'Shelf for your books and other items',
        Description:
          'Go to the search section and choose the one that suits you',
      },
      InstructionsClaim: {
        Header: 'Did you find something interesting to claim?',
        Description:
          'Use the mobile version of the application and quickly and easily take books and other items with this application',
      },
      NavbarReader: {
        Home: 'Home',
        Search: 'Search',
        'Donate to the library': 'Donate to the library',
        'History of claim': 'History of claim',
        'History of donate': 'History of donate',
        Settings: 'Settings',
        'Log out': 'Log out',
      },
      NavbarManager: {
        Home: 'Home',
        Readers: 'Readers',
        Library: 'Library',
        'Donates from user': 'Donates from user',
        'Add item to library': 'Add item to library',
        Settings: 'Settings',
        'Log out': 'Log out',
      },
      Search: {
        Placeholder: 'Search by book or author',
        Scan: 'Scan a code',
        UsernamePlaceholder: 'Search by user name',
      },
      Start: {
        ChooseLocation: 'Your current location',
      },
      Settings: {
        Title: 'Settings',
        Desc: 'Make applications as comfortable as possible for yourself! All changes are saved automatically',
        Location: 'Location',
        Language: 'Language',
        Notification: 'Notification',
      },
      Readers: {
        Title: 'All users',
        Description:
          'For detailed information and interaction with the user, go to his card',
        SingleUser: {
          ClaimHistory: 'Claim history:',
          ClaimNow: 'Claim now:',
          Overdue: 'Overdue:',
          Item: 'item',
          Items: 'items',
        },
      },
      ManagerInfoCard: {
        Title: {
          Overdue: 'Overdue',
          Donates: 'Donates',
          Notifications: 'New user notifications',
        },
        Description: {
          Overdue: 'The following users have not turned in their books',
          Donates: 'New arrivals awaiting your confirmation',
          Notifications: 'Problems faced by users',
          More: 'more',
          Library: 'Open library statistics',
        },
        Link: {
          Overdue: 'See all overdue',
          Donates: 'See all donates',
          Notifications: 'See all notifications',
          Answer: 'Answer',
        },
        FieldDescription: {
          Overdue: 'Was overdue by',
          Donates: 'Was donated by',
        },
      },
      UserCard: {
        Position: 'Position:',
        Table: {
          AllItems: 'All items',
          ReturnTill: 'Return till:',
          ReturnedAt: 'Returned at:',
          ItemName: 'Item name',
          Deadline: 'Deadline',
          State: 'State',
          Overdue: 'Overdue',
          Returned: 'Returned',
          Claim: 'Claim',
          Prolong: 'Prolong',
          ShelfOf: 'Shelf of ',
          BooksAndItems: "'s books and other items",
        },
        ClaimList: 'Claim list',
        ClaimListDescription:
          'List of all items user have taken for all the time',
        Notifications: 'Notifications',
        NotificationsDescription: 'All notifications sent by the user',
        BlockReason: 'Reason for blocking: ',
        Today: 'Today',
        Earlier: 'Earlier',
        BlockUser: 'Block user',
        UnblockUser: 'Unblock user',
        CreateNotification: 'Create notification',
        MakeManager: 'Make manager',
        MakeReader: 'Make reader',
        hAgo: 'h ago',
        dAgo: 'd ago',
      },
      Notifications: {
        Managers: {
          MainTitle: 'Notifications',
          MainDescription: 'New notifications are waiting for you',
        },
        Today: 'Today',
        Earlier: 'Earlier',
      },
      PopUps: {
        NotFoundByIdentifier:
          "Sorry, we didn't find a book with that identifier",
      },
      Block: {
        Warning: 'Warning!',
        YBlock: 'Yes, block',
        YUnblock: 'Yes, unblock',
        SureUnblock: 'Are you sure you want to unblock the user ',
        SureBlock: 'Are you sure you want to block the user ',
        InLibrary: ' in library?',
        BlockUser: 'Block user',
        Reason: 'Specify the reason for the block. User will be able to see it',
        TooManyDebts: 'Too many debts',
        Fired: 'The user has been fired',
        Other: 'Other reason',
        FullOther: 'Other reason (specify in message)',
        Opps: 'Opps! Your page has been blocked',
        ReasonForBlock: 'Reason for blocking:',
      },
      ClaimHistory: {
        Title: 'History of your claim',
        Desc: 'List of items you have taken for all time',
      },
      AnswerModal: {
        Title: 'Reply to notification',
        SubTitle: 'Choose a ready-made message or write your own:',
        DescMessage: 'Own message:',
        SendBtn: 'Send notification',
      },
      DonateHistory: {
        Title: 'History of your donate',
        Desc: 'List of items you have donated to the library',
      },
    },
  },
  ru: {
    translation: {
      Back: 'Назад',
      Loading: 'Загрузка...',
      Cancel: 'Закрыть',
      EmptyListItems: {
        Header: 'Полка для ваших книг и других предметов',
        Description:
          'Зайдите в раздел поиска и выберите подходящий Вам предмет',
      },
      InstructionsClaim: {
        Header: 'Вы нашли что-нибудь интересное?',
        Description:
          'Используйте мобильную версию приложения и быстро и легко берите книги и другие предметы с этим приложением',
      },
      NavbarReader: {
        Home: 'Домой',
        Search: 'Поиск',
        'Donate to the library': 'Пожертвовать библиотеке',
        'History of claim': 'История клеймов',
        'History of donate': 'История донатов',
        Settings: 'Настройки',
        'Log out': 'Выход',
      },
      NavbarManager: {
        Home: 'Домой',
        Readers: 'Читатели',
        'Books/stuff': 'Книги/предметы',
        'Donates from user': 'Донаты от пользователей',
        'Create new item': 'Создать новый предмет',
        Setting: 'Настройки',
        'Log out': 'Выход',
      },
      Search: {
        Placeholder: 'Поиск по книге или автору',
        Scan: 'Сканировать',
        UsernamePlaceholder: 'Поиск по имени пользователя',
      },
      Start: {
        ChooseLocation: 'Ваше текущее местоположение',
      },
      Settings: {
        Title: 'Настройки',
        Desc: 'Сделайте приложения максимально комфортными для себя! Все изменения сохраняются автоматически',
        Location: 'Местоположение',
        Language: 'Язык',
        Notification: 'Уведомления',
      },
      Readers: {
        Title: 'Все пользователи',
        Description:
          'Для подробной информации и взаимодействия с пользователем, перейдите к его карточке',
        SingleUser: {
          ClaimHistory: 'История:',
          ClaimNow: 'На руках:',
          Overdue: 'Просрочены:',
          Item: 'предмет',
          Items: 'предмета',
        },
      },
      ManagerInfoCard: {
        Title: {
          Overdue: 'Просроченные',
          Donates: 'Пожертвования',
          Notifications: 'Новые уведомления от пользователей',
        },
        Description: {
          Overdue: 'Эти пользователи не вернули свои книги вовремя',
          Donates: 'Новые поступления от пользователей',
          Notifications: 'Проблемы, описанные пользователями',
          More: 'ещё',
          Library: 'Открыть статистику библиотеки',
        },
        Link: {
          Overdue: 'Все просроченные',
          Donates: 'Все пожертвования',
          Notifications: 'Все уведомления',
          Answer: 'Ответить',
        },
        FieldDescription: {
          Overdue: 'Просрочил:',
          Donates: 'Пожертвовал:',
        },
      },
      UserCard: {
        Position: 'Должность:',
        Table: {
          AllItems: 'Все вещи',
          ReturnTill: 'Вернуть до:',
          ReturnedAt: 'Было возвращено:',
          ItemName: 'Название',
          Deadline: 'Срок возвращения',
          State: 'Статус',
          Overdue: 'Просрочено',
          Returned: 'Возвращено',
          Claim: 'На руках',
          Prolong: 'Продлено',
          ShelfOf: 'Полка книг и вещей пользователя ',
          BooksAndItems: '',
        },
        ClaimList: 'Список взятых вещей',
        ClaimListDescription:
          'Список всех вещей, которые когда-либо брал пользователь',
        Notifications: 'Уведомления',
        NotificationsDescription: 'Все уведомления от пользователя',
        BlockReason: 'Причина блокировки: ',
        Today: 'Сегодня',
        Earlier: 'Ранее',
        BlockUser: 'Заблокировать',
        UnblockUser: 'Разблокировать',
        CreateNotification: 'Создать уведомление',
        MakeManager: 'Сделать менеджером',
        MakeReader: 'Сделать читателем',
        hAgo: 'ч назад',
        dAgo: 'д назад',
      },
      Notifications: {
        Managers: {
          MainTitle: 'Уведомления',
          MainDescription: 'Новые уведомления ждут вас',
        },
        Today: 'Сегодня',
        Earlier: 'Ранее',
      },
      PopUps: {
        NotFoundByIdentifier: 'Упс, мы не нашли книгу с таким идентификатором',
      },
      Block: {
        Warning: 'Внимание!',
        YBlock: 'Да, заблокировать',
        YUnblock: 'Да, разблокировать',
        SureUnblock: 'Вы уверены, что хотите разблокировать пользователя ',
        SureBlock: 'Вы уверены, что хотите заблокировать пользователя ',
        InLibrary: ' в библиотеке?',
        BlockUser: 'Заблокировать пользователя',
        Reason: 'Опишите причину блокировки. Пользователь увидит её',
        TooManyDebts: 'Слишком много долгов',
        Fired: 'Пользователь был уволен',
        Other: 'Другая причина',
        FullOther: 'Другая причина (опишите в сообщении)',
        Opps: 'Упс! Ваша страница заблокирована',
        ReasonForBlock: 'Причина блокировки:',
      },
      ClaimHistory: {
        Title: 'История взятых вами книг',
        Desc: 'Список предметов, которые вы взяли за все время',
      },
      AnswerModal: {
        Title: 'Ответить на уведомление',
        SubTitle: 'Выберите готовое сообщение или напишите свое собственное:',
        DescMessage: 'Собственное сообщение:',
        SendBtn: 'Отправить уведомление',
      },
      DonateHistory: {
        Title: 'История ваших пожертвований',
        Desc: 'Список вещей, пожертвованных вами в библиотеку',
      },
    },
  },
};
