name: Deploy_webapp
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache package-lock.json
        id: cache-package-lock
        uses: actions/cache@v3
        with:
          path: package-lock.json
          key: ${{ runner.os }}-staging-package-lock-${{ hashFiles('**/package-lock.json') }}

      - name: SSH Git pull & npm install
        if: steps.cache-package-lock.outputs.cache-hit != 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: bash mimir/scripts/deploy_webapp.sh

      - name: SSH Git pull
        if: steps.cache-package-lock.outputs.cache-hit == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: bash mimir/scripts/deploy_webapp_pull_only.sh
